### ISSUE TITLE
you can still see what tags are hidden when the overrides are disabled

### ISSUE THREAD

**Issue by RyanCR03** [MaheEvil/SomeOrdinaryTweaks#1] opened 2021-12-23 21:34 UTC
^

**Comment by AdelinaM17n** [comment] 2021-12-24 03:04
Hey could you like, provide bit more info? or a screenshot?

**Comment by AdelinaM17n** [comment] 2021-12-25 10:13
you have provided no substantial info and I do not understand what the issue is, I am closing this issue.
Feel free to reopen the issue/comment with some info or create a new issue.

**Closed as completed by AdelinaM17n** 2021-12-25 10:13 UTC
Labels: Info needed
